---

- name: install zsh
  apt:
    name: zsh

- name: usermod -s /bin/zsh
  command: "usermod -s /bin/zsh {{ ssh_user }}"
  args:
    creates: "/home/{{ ssh_user}}/.zshrc"

- name: copy zshrc
  copy:
    src: zshrc
    dest: "/home/{{ ssh_user }}/.zshrc"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"

