---

- name: install curl docker
  shell: "curl -sSL https://get.docker.com | sh"
  args:
    creates: /usr/bin/docker

- name: install pip3
  apt:
    name:
      - python3-dev
      - python3-pip

- name: install docker-compose
  pip:
    name: docker-compose

- name: systemctl start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: user add sudo,docker group
  user:
    name: "{{ ssh_user }}"
    groups: sudo,docker
