---

- name: install curl docker
  shell: "curl -sSL https://get.docker.com | sh"
  args:
    creates: /usr/bin/docker

- name: install pip3
  apt:
    name:
      - python3-dev
      - python3-pip

- name: install docker-compose
  pip:
    name: docker-compose

